server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:mysql://101.133.226.28:3306/mytest?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: stt19960604
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    password: fjy19970408
    url: 101.133.226.28
    port: 6379
    lettuce:
      pool:
        max-active: 8