server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost/mytest?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    password:
    host: 192.168.148.131
    port: 6379
    lettuce:
      pool:
        max-active: 8